import { ResourceItem, Weapon, ShelterStructure, LevelConfig, Animal } from '../types';

export const RESOURCE_ITEMS: Record<string, ResourceItem> = {
  wood: {
    id: 'wood',
    name: 'Hardwood Log',
    nameHi: 'काठ की लकड़ी',
    category: 'WOOD',
    points: 20,
    icon: '🪵',
    color: '#8b5a2b',
    description: 'Sturdy jungle timber used for weapons and shelters.',
    descriptionHi: 'मजबूत जंगली लकड़ी, हथियार और घर बनाने के काम आती है।',
  },
  stone: {
    id: 'stone',
    name: 'Granite Stone',
    nameHi: 'ग्रेनाइट पत्थर',
    category: 'STONE',
    points: 25,
    icon: '🪨',
    color: '#78716c',
    description: 'Heavy durable rocks for crafting sharp spears and fortifications.',
    descriptionHi: 'नुकीले भाले और मजबूत दीवारें बनाने हेतु भारी पत्थर।',
  },
  fiber: {
    id: 'fiber',
    name: 'Jungle Vines',
    nameHi: 'जंगली बेल व रेशे',
    category: 'FIBER',
    points: 15,
    icon: '🌿',
    color: '#22c55e',
    description: 'Flexible cords to bind tools, bowstrings, and thatch roofs.',
    descriptionHi: 'धनुष की डोरी, औजार बांधने और छप्पर छाने के लिए रेशे।',
  },
  berries: {
    id: 'berries',
    name: 'Wild Island Berries',
    nameHi: 'जंगली फल व बेर',
    category: 'FOOD',
    points: 15,
    icon: '🫐',
    color: '#a855f7',
    description: 'Sweet nutrient-rich fruits that restore hunger and health.',
    descriptionHi: 'ऊर्जा और स्वास्थ्य (HP) बढ़ाने वाले मीठे जंगली फल।',
  },
  coconut: {
    id: 'coconut',
    name: 'Fresh Coconut',
    nameHi: 'ताजा नारियल',
    category: 'FOOD',
    points: 25,
    icon: '🥥',
    color: '#d97706',
    description: 'Quenches thirst, completely recharges stamina and energy.',
    descriptionHi: 'प्यास बुझाए, ऊर्जा और दौड़ने की ताकत तुरंत वापस लाए।',
  },
  iron: {
    id: 'iron',
    name: 'Iron Ore',
    nameHi: 'लोहा अयस्क',
    category: 'IRON',
    points: 50,
    icon: '⛏️',
    color: '#94a3b8',
    description: 'Dense metal from island caves to forge sharp blades and spikes.',
    descriptionHi: 'धारदार हथियार और मजबूत कीलें बनाने के लिए ठोस धातु।',
  },
  crystal: {
    id: 'crystal',
    name: 'Strange Island Crystal',
    nameHi: 'रहस्यमयी द्वीप रत्न',
    category: 'CRYSTAL',
    points: 80,
    icon: '💎',
    color: '#06b6d4',
    description: 'Glows with alien energy; needed for advanced weapons and wards.',
    descriptionHi: 'रहस्यमयी ऊर्जा से चमकता रत्न, शक्तिशाली अस्त्रों हेतु आवश्यक।',
  },
  beast_claw: {
    id: 'beast_claw',
    name: 'Strange Beast Claw',
    nameHi: 'अजीब जानवर का पंजा',
    category: 'BEAST_DROP',
    points: 60,
    icon: '🐾',
    color: '#f43f5e',
    description: 'Lethal serrated claw scavenged from fallen island predators.',
    descriptionHi: 'मारे गए जानवर से मिला नुकीला और खतरनाक पंजा।',
  },
  venom_sac: {
    id: 'venom_sac',
    name: 'Toxic Venom Sac',
    nameHi: 'विषैली ग्रंथि',
    category: 'BEAST_DROP',
    points: 75,
    icon: '🧪',
    color: '#84cc16',
    description: 'Corrosive poison harvested from mutant crawlers.',
    descriptionHi: 'अजीब कीड़ों और छिपकलियों से निकला घातक जहर।',
  },
  beast_hide: {
    id: 'beast_hide',
    name: 'Armored Beast Hide',
    nameHi: 'मोटी खाल व कवच',
    category: 'BEAST_DROP',
    points: 70,
    icon: '🛡️',
    color: '#c2410c',
    description: 'Thick leathery hide used for tough shelters and defenses.',
    descriptionHi: 'मजबूत और सुरक्षित रहने की जगह बनाने के लिए मोटी चमड़ी।',
  },
};

export const WEAPONS: Record<string, Weapon> = {
  fists: {
    id: 'fists',
    name: 'Bare Fists',
    nameHi: 'खाली हाथ / मुक्के',
    damage: 6,
    range: 36,
    attackSpeed: 380,
    type: 'MELEE',
    icon: '👊',
    cost: {},
    description: 'Desperate unarmed combat. Minimal damage and range.',
    descriptionHi: 'बिना हथियार के मुक्के। बहुत कम नुकसान।',
  },
  wooden_club: {
    id: 'wooden_club',
    name: 'Heavy Spiked Club',
    nameHi: 'काठ की लाठी / गदा',
    damage: 18,
    range: 54,
    attackSpeed: 420,
    type: 'MELEE',
    specialEffect: 'KNOCKBACK',
    icon: '🏏',
    cost: { wood: 4, fiber: 2 },
    description: 'Crafted from solid hardwood. Knocks strange beasts back!',
    descriptionHi: 'भारी काठ से बनी लाठी। वार करने पर जानवरों को पीछे धकेलती है।',
  },
  stone_spear: {
    id: 'stone_spear',
    name: 'Sharp Stone Spear',
    nameHi: 'नुकीला पत्थर का भाला',
    damage: 32,
    range: 78,
    attackSpeed: 480,
    type: 'THRUST',
    icon: '🔱',
    cost: { wood: 6, stone: 4, fiber: 3 },
    description: 'Long reaching thrust weapon that keeps dangerous predators at bay.',
    descriptionHi: 'दूर तक वार करने वाला भाला, खतरनाक जानवरों को दूर रखता है।',
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Hunter\'s Bow & Arrows',
    nameHi: 'शिकारी तीर-धनुष',
    damage: 38,
    range: 240,
    attackSpeed: 600,
    type: 'RANGED',
    projectileSpeed: 9,
    icon: '🏹',
    cost: { wood: 8, fiber: 6, stone: 3 },
    description: 'Ranged bow to safely eliminate deadly beasts from a distance.',
    descriptionHi: 'दूर से ही खतरनाक जानवरों को ढेर करने वाला तीर-धनुष।',
  },
  fire_torch: {
    id: 'fire_torch',
    name: 'Blazing Fire Torch',
    nameHi: 'जलती अग्नि मशाल',
    damage: 26,
    range: 48,
    attackSpeed: 400,
    type: 'MELEE',
    specialEffect: 'FIRE',
    icon: '🔥',
    cost: { wood: 5, fiber: 4, berries: 2 },
    description: 'Lights the darkness and sets strange creatures aflame. Beasts fear fire!',
    descriptionHi: 'अंधेरे में उजाला करे और जानवरों को जलाए। जानवर आग से डरते हैं!',
  },
  machete: {
    id: 'machete',
    name: 'Forged Iron Machete',
    nameHi: 'जंगली लोहे की तलवार',
    damage: 54,
    range: 58,
    attackSpeed: 340,
    type: 'MELEE',
    icon: '🗡️',
    cost: { iron: 4, wood: 4, beast_claw: 2 },
    description: 'Razor sharp iron blade that swiftly cuts through dense hide.',
    descriptionHi: 'तेज धारदार लोहे की तलवार, एक झटके में जानवरों पर प्रहार करती है।',
  },
  obsidian_blade: {
    id: 'obsidian_blade',
    name: 'Obsidian Beast Cleaver',
    nameHi: 'ऑब्सिडियन खड्ग',
    damage: 82,
    range: 65,
    attackSpeed: 380,
    type: 'MELEE',
    specialEffect: 'KNOCKBACK',
    icon: '⚔️',
    cost: { iron: 6, crystal: 3, beast_claw: 3 },
    description: 'Infused with island crystal power. Massive critical damage.',
    descriptionHi: 'रहस्यमयी क्रिस्टल से तराशी गई तलवार। भारी विनाशकारी नुकसान!',
  },
  plasma_spear: {
    id: 'plasma_spear',
    name: 'Titan Plasma Lance',
    nameHi: 'महादैत्य संहारक भाला',
    damage: 130,
    range: 95,
    attackSpeed: 450,
    type: 'THRUST',
    specialEffect: 'FIRE',
    icon: '⚡',
    cost: { crystal: 6, iron: 8, beast_hide: 4, venom_sac: 3 },
    description: 'Ultimate weapon against high-level titan beasts.',
    descriptionHi: 'उच्च स्तर के भयानक दैत्यों को मात देने वाला अंतिम दिव्य अस्त्र।',
  },
};

export const SHELTERS: Record<string, ShelterStructure> = {
  campfire: {
    id: 'campfire',
    name: 'Survival Campfire',
    nameHi: 'अलाव / कैम्पफायर',
    category: 'CAMPFIRE',
    maxHp: 160,
    radius: 110,
    defenseBoost: 15,
    healRate: 3.5, // HP per sec
    frightensBeasts: true,
    icon: '⛺',
    cost: { wood: 5, stone: 3 },
    description: 'Provides warm light, regenerates health, and wards off nocturnal beasts.',
    descriptionHi: 'रोशनी देता है, आपकी जान (HP) बढ़ाता है और जंगली जानवरों को भगाता है।',
  },
  leaf_hut: {
    id: 'leaf_hut',
    name: 'Thatched Leaf Shelter',
    nameHi: 'पत्तों की झोपड़ी (आश्रय)',
    category: 'HUT',
    maxHp: 300,
    radius: 120,
    defenseBoost: 25,
    healRate: 5,
    frightensBeasts: false,
    icon: '🛖',
    cost: { wood: 8, fiber: 6, stone: 4 },
    description: 'A cozy sanctuary. Take shelter inside to rapidly recover stamina and health.',
    descriptionHi: 'सुरक्षित रहने का ठिकाना। अंदर खड़े होने पर तेजी से सेहत सुधरती है।',
  },
  spike_wall: {
    id: 'spike_wall',
    name: 'Spiked Wooden Barricade',
    nameHi: 'कांटेदार बाड़ / दीवार',
    category: 'SPIKE',
    maxHp: 450,
    radius: 70,
    defenseBoost: 35,
    healRate: 0,
    frightensBeasts: false,
    icon: '🪵',
    cost: { wood: 10, fiber: 4, stone: 4 },
    description: 'Blocks aggressive charging beasts and damages them when they strike.',
    descriptionHi: 'रास्ता रोकती है। हमला करने पर जानवर इसके कांटों से जख्मी होते हैं।',
  },
  watchtower: {
    id: 'watchtower',
    name: 'Elevated Lookout Post',
    nameHi: 'निगरानी मचान / चौकी',
    category: 'TOWER',
    maxHp: 550,
    radius: 160,
    defenseBoost: 40,
    healRate: 4,
    frightensBeasts: true,
    icon: '🗼',
    cost: { wood: 14, iron: 3, fiber: 8 },
    description: 'Elevated platform offering strategic sight and high defense against beasts.',
    descriptionHi: 'ऊंचा मचान, दूर से आने वाले जानवरों को देखने और सुरक्षित रहने हेतु।',
  },
  stone_fortress: {
    id: 'stone_fortress',
    name: 'Reinforced Citadel',
    nameHi: 'अभेद्य पत्थर का किला',
    category: 'STONE_FORT',
    maxHp: 1100,
    radius: 180,
    defenseBoost: 60,
    healRate: 8,
    frightensBeasts: true,
    icon: '🏰',
    cost: { stone: 18, iron: 8, beast_hide: 4, wood: 12 },
    description: 'Impenetrable fortress. Maximum defense and passive regeneration.',
    descriptionHi: 'उच्च स्तर के भयानक दैत्यों से बचने के लिए सबसे मजबूत सुरक्षित किला।',
  },
};

export const ANIMAL_SPECIES: Record<string, Omit<Animal, 'id' | 'x' | 'y' | 'vx' | 'vy' | 'behavior' | 'wanderTarget' | 'stateTimer' | 'lastAttackTime'>> = {
  venom_crawler: {
    typeId: 'venom_crawler',
    name: 'Venom Crawler',
    nameHi: 'विषैला क्रॉलर (अजीब कीट)',
    size: 16,
    hp: 45,
    maxHp: 45,
    speed: 1.8,
    damage: 10,
    attackCooldown: 1200,
    aggroRadius: 160,
    color: '#84cc16',
    glowColor: '#4ade80',
    legs: 6,
    drops: [
      { itemId: 'venom_sac', count: 1, chance: 0.8 },
      { itemId: 'fiber', count: 2, chance: 0.9 },
    ],
    pointsOnKill: 45,
  },
  horned_wolf: {
    typeId: 'horned_wolf',
    name: 'Feral Horned Wolf',
    nameHi: 'सींग वाला जंगली भेड़िया',
    size: 20,
    hp: 80,
    maxHp: 80,
    speed: 2.3,
    damage: 16,
    attackCooldown: 1000,
    aggroRadius: 210,
    color: '#991b1b',
    glowColor: '#ef4444',
    legs: 4,
    hasHorns: true,
    hasTail: true,
    drops: [
      { itemId: 'beast_claw', count: 1, chance: 0.75 },
      { itemId: 'beast_hide', count: 1, chance: 0.6 },
    ],
    pointsOnKill: 75,
  },
  spike_boar: {
    typeId: 'spike_boar',
    name: 'Armored Spike Boar',
    nameHi: 'कांटेदार जंगली सूअर',
    size: 22,
    hp: 130,
    maxHp: 130,
    speed: 2.5,
    damage: 24,
    attackCooldown: 1400,
    aggroRadius: 230,
    color: '#7c2d12',
    glowColor: '#ea580c',
    legs: 4,
    hasHorns: true,
    drops: [
      { itemId: 'beast_hide', count: 2, chance: 0.9 },
      { itemId: 'beast_claw', count: 1, chance: 0.8 },
    ],
    pointsOnKill: 110,
  },
  shadow_stalker: {
    typeId: 'shadow_stalker',
    name: 'Shadow Stalker',
    nameHi: 'छाया शिकारी (अजीब तेंदुआ)',
    size: 19,
    hp: 110,
    maxHp: 110,
    speed: 2.9,
    damage: 28,
    attackCooldown: 900,
    aggroRadius: 260,
    color: '#581c87',
    glowColor: '#c084fc',
    legs: 4,
    hasTail: true,
    drops: [
      { itemId: 'crystal', count: 1, chance: 0.5 },
      { itemId: 'beast_claw', count: 2, chance: 0.9 },
    ],
    pointsOnKill: 150,
  },
  toxic_hydra: {
    typeId: 'toxic_hydra',
    name: 'Mutant Toxic Hydra',
    nameHi: 'विशाल विष-छिपकली (हाइड्रा)',
    size: 28,
    hp: 240,
    maxHp: 240,
    speed: 2.1,
    damage: 38,
    attackCooldown: 1500,
    aggroRadius: 280,
    color: '#065f46',
    glowColor: '#10b981',
    legs: 6,
    hasTail: true,
    drops: [
      { itemId: 'venom_sac', count: 3, chance: 1.0 },
      { itemId: 'crystal', count: 2, chance: 0.8 },
    ],
    pointsOnKill: 260,
  },
  titan_chimera: {
    typeId: 'titan_chimera',
    name: 'Titan Chimera Beast',
    nameHi: 'विशालकाय रहस्यमयी महादैत्य',
    size: 36,
    hp: 450,
    maxHp: 450,
    speed: 2.4,
    damage: 55,
    attackCooldown: 1600,
    aggroRadius: 320,
    color: '#831843',
    glowColor: '#f43f5e',
    legs: 4,
    hasWings: true,
    hasHorns: true,
    hasTail: true,
    drops: [
      { itemId: 'crystal', count: 3, chance: 1.0 },
      { itemId: 'beast_hide', count: 3, chance: 1.0 },
      { itemId: 'beast_claw', count: 3, chance: 1.0 },
    ],
    pointsOnKill: 500,
  },
};

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: 'Level 1: The Stranded Shore',
    nameHi: 'स्तर १: सुनसान समुद्री किनारा',
    description: 'You woke up alone after a shipwreck. Search the sands and jungle edges for wood and stone. Build your first shelter and craft a club to survive the crawling beasts!',
    descriptionHi: 'जहाज टूटने के बाद आप अकेले इस रहस्यमयी द्वीप पर पहुंचे हैं। जंगल में लकड़ी और पत्थर तलाशें। लाठी बनाएं और अपनी सुरक्षा के लिए पहली झोपड़ी या अलाव बनाएं!',
    pointsRequired: 250,
    resourcesToGather: 6,
    structuresToBuild: 1,
    beastsToDefeat: 2,
    animalSpawnInterval: 8000,
    maxConcurrentAnimals: 4,
    animalPool: ['venom_crawler', 'horned_wolf'],
    dangerRating: 'LOW',
    ambientTheme: 'TROPICAL',
    timeCycleSpeed: 90,
  },
  {
    level: 2,
    name: 'Level 2: The Whispering Jungle',
    nameHi: 'स्तर २: गहरा और भयानक जंगल',
    description: 'The jungle grows denser and strange howling echoes from the trees. Fast spike boars and vicious wolves stalk in packs. Craft a spear and bow, and reinforce your base with spike walls!',
    descriptionHi: 'जंगल और गहरा हो चुका है और अजीब डरावनी आवाजें आ रही हैं। सींग वाले भेड़िए और कांटेदार सूअर आ रहे हैं। भाला और तीर-धनुष बनाएं तथा कांटेदार बाड़ खड़ी करें!',
    pointsRequired: 700,
    resourcesToGather: 12,
    structuresToBuild: 2,
    beastsToDefeat: 5,
    animalSpawnInterval: 6500,
    maxConcurrentAnimals: 6,
    animalPool: ['venom_crawler', 'horned_wolf', 'spike_boar'],
    dangerRating: 'MEDIUM',
    ambientTheme: 'MURKY_SWAMP',
    timeCycleSpeed: 80,
  },
  {
    level: 3,
    name: 'Level 3: Shadow of the Mutants',
    nameHi: 'स्तर ३: उत्परिवर्ती छाया और जहर का प्रकोप',
    description: 'Strange purple crystals pulse in the earth. Elusive Shadow Stalkers and multi-legged Toxic Hydras emerge when night falls. Forge iron weapons and erect a high watchtower!',
    descriptionHi: 'जमीन से अजीब नीले-बैंगनी क्रिस्टल निकल रहे हैं। छाया शिकारी और विशाल विष-छिपकलियां अंधेरा होते ही हमला करती हैं। लोहे की तलवार बनाएं और मचान तैयार करें!',
    pointsRequired: 1500,
    resourcesToGather: 18,
    structuresToBuild: 3,
    beastsToDefeat: 8,
    animalSpawnInterval: 5000,
    maxConcurrentAnimals: 8,
    animalPool: ['horned_wolf', 'spike_boar', 'shadow_stalker', 'toxic_hydra'],
    dangerRating: 'HIGH',
    ambientTheme: 'CORRUPTED_JUNGLE',
    timeCycleSpeed: 70,
  },
  {
    level: 4,
    name: 'Level 4: Volcanic Titan Awakening',
    nameHi: 'स्तर ४: ज्वालामुखी का कहर और महादैत्य',
    description: 'The island trembles! Red lightning fractures the sky as the legendary Titan Chimera awakens alongside aggressive predator packs. Build an impenetrable Stone Fortress to survive!',
    descriptionHi: 'द्वीप कांप रहा है! आकाश में लाल बिजलियां चमक रही हैं और विशालकाय महादैत्य जाग चुका है। जीवित रहने के लिए अभेद्य पत्थर का किला बनाएं और सर्वोच्च अस्त्र तैयार करें!',
    pointsRequired: 2800,
    resourcesToGather: 25,
    structuresToBuild: 4,
    beastsToDefeat: 12,
    animalSpawnInterval: 4000,
    maxConcurrentAnimals: 11,
    animalPool: ['spike_boar', 'shadow_stalker', 'toxic_hydra', 'titan_chimera'],
    dangerRating: 'EXTREME',
    ambientTheme: 'VOLCANIC_RUINS',
    timeCycleSpeed: 60,
  },
  {
    level: 5,
    name: 'Level 5: Endless Blood Moon Sanctuary',
    nameHi: 'स्तर ५: रक्त चंद्र और अनंत अस्तित्व संग्राम',
    description: 'Perpetual nocturnal eclipse. Mutated beasts spawn with doubled fury. Can you claim total mastery of the island and become the ultimate apex survivor?',
    descriptionHi: 'लगातार रक्त चंद्र ग्रहण! सारे अजीब जानवर दोगुनी ताकत और तेजी से टूट पड़ेंगे। क्या आप इस भयानक द्वीप के स्वामी बन कर जीवित रह पाएंगे?',
    pointsRequired: 5000,
    resourcesToGather: 35,
    structuresToBuild: 5,
    beastsToDefeat: 20,
    animalSpawnInterval: 3200,
    maxConcurrentAnimals: 14,
    animalPool: ['venom_crawler', 'horned_wolf', 'spike_boar', 'shadow_stalker', 'toxic_hydra', 'titan_chimera'],
    dangerRating: 'NIGHTMARE',
    ambientTheme: 'VOLCANIC_RUINS',
    timeCycleSpeed: 50,
  },
];

export const UI_TEXT = {
  hi: {
    appTitle: 'आइसलैंड सर्वाइवर: अजीब जानवर',
    subtitle: 'अकेले द्वीप पर फंसे एक इंसान का भयानक संघर्ष',
    start: 'खेल शुरू करें',
    resume: 'खेल जारी रखें',
    pause: 'रोकें (Pause)',
    paused: 'खेल रुका हुआ है',
    restart: 'पुनः प्रारंभ करें',
    craft: 'हथियार व आश्रय निर्माण',
    inventory: 'सामान (पोटली)',
    shelterMenu: 'रहने की जगह (आश्रय)',
    weaponsMenu: 'हथियार निर्माण',
    supplies: 'औषधि व आहार',
    health: 'जीवन (HP)',
    stamina: 'ऊर्जा (Stamina)',
    hunger: 'भूख / पोषण',
    points: 'अंक (Points)',
    score: 'कुल स्कोर',
    level: 'स्तर (Level)',
    danger: 'खतरे का स्तर',
    day: 'दिन',
    night: 'रात',
    dusk: 'संध्याकाल',
    bloodMoon: 'रक्त चंद्र',
    objectives: 'स्तर के लक्ष्य:',
    gatherGoal: 'जंगल में सामान ढूंढें:',
    buildGoal: 'रहने का सुरक्षित स्थान बनाएं:',
    defeatGoal: 'अजीब जानवरों को मारें:',
    pointsGoal: 'आवश्यक अंक (Score):',
    completeLevel: 'स्तर पूर्ण हुआ!',
    nextLevel: 'अगले और अधिक खतरनाक स्तर पर जाएं',
    gameOver: 'आप वीरगति को प्राप्त हुए!',
    gameOverDesc: 'अजीब जानवरों ने आपको घेर लिया। फिर से प्रयास करें और बेहतर तैयारी करें!',
    safeZone: 'सुरक्षित आश्रय (Safe Haven)',
    safeZoneDesc: 'रक्षा +% और तेजी से जीवन सुधार!',
    controlsHelp: 'नियंत्रण: चलने के लिए W,A,S,D या तीर कुंजी | हमला करने के लिए Space या बायाँ क्लिक | सामान उठाने के लिए पास जाएं (E)',
    mobileAttack: 'हमला (Attack)',
    mobileCraft: 'निर्माण (Craft)',
    mobileInteract: 'सामान उठाएं (Pick)',
    placeStructure: 'यहाँ स्थापित करें (Click on Map)',
    cancelPlacement: 'रद्द करें',
    insufficientMaterials: 'सामग्री की कमी है!',
    craftedSuccess: 'सफलतापूर्वक निर्माण किया गया!',
    eatBerries: 'फल खाएं (HP +15)',
    drinkCoconut: 'नारियल पिएं (Stamina 100%)',
    strangeAnimalApproaching: 'सावधान! अजीब जानवर पास आ रहा है!',
    levelEscalationWarning: 'चेतावनी: अगला स्तर और भी भयानक है! जानवर और आक्रामक होंगे!',
  },
  en: {
    appTitle: 'Island Survivor: Strange Beasts',
    subtitle: 'Stranded alone on an uncharted island crawling with predators',
    start: 'Start Survival',
    resume: 'Resume Game',
    pause: 'Pause',
    paused: 'Game Paused',
    restart: 'Try Again',
    craft: 'Craft & Build',
    inventory: 'Inventory',
    shelterMenu: 'Shelters & Bases',
    weaponsMenu: 'Weapon Forge',
    supplies: 'Rations & Medicine',
    health: 'Health',
    stamina: 'Stamina',
    hunger: 'Fullness',
    points: 'Score Points',
    score: 'Total Score',
    level: 'Level',
    danger: 'Danger Rating',
    day: 'Day',
    night: 'Night',
    dusk: 'Dusk',
    bloodMoon: 'Blood Moon',
    objectives: 'Level Objectives:',
    gatherGoal: 'Scavenge Jungle Items:',
    buildGoal: 'Construct Shelters:',
    defeatGoal: 'Defeat Strange Beasts:',
    pointsGoal: 'Required Score Points:',
    completeLevel: 'Level Cleared!',
    nextLevel: 'Enter More Dangerous Level',
    gameOver: 'Survivor Fallen',
    gameOverDesc: 'The strange island predators overwhelmed you. Re-arm and try again!',
    safeZone: 'Safe Sanctuary',
    safeZoneDesc: 'Defense boost & rapid health regen active!',
    controlsHelp: 'Controls: W,A,S,D or Arrow keys to move | Space or Left Click to Attack | E to collect items | Click ground to build',
    mobileAttack: 'Attack',
    mobileCraft: 'Craft',
    mobileInteract: 'Interact / Gather',
    placeStructure: 'Place Here (Click on Map)',
    cancelPlacement: 'Cancel',
    insufficientMaterials: 'Missing required resources!',
    craftedSuccess: 'Crafted & Deployed!',
    eatBerries: 'Eat Berries (+15 HP)',
    drinkCoconut: 'Drink Coconut (Full Stamina)',
    strangeAnimalApproaching: 'Warning! Strange beast approaching!',
    levelEscalationWarning: 'Warning: Next level is significantly more dangerous! Mutants are evolving!',
  },
};
